Repository dnd-side-project/dnd-11th-3-frontend, pull requests merged in 2024-08, with the labels that each got.

#12 [#10] chore: add setting for storybook and deploy storybook with netlify
  .gitignore
  .husky/_/husky.sh
  package-lock.json
  package.json
  packages/client/next.config.mjs
  packages/client/package.json
  packages/gmi-design-system/.eslintrc.json
  packages/gmi-design-system/.storybook/main.js
  packages/gmi-design-system/.storybook/preview-head.html
  packages/gmi-design-system/.storybook/preview.js
  packages/gmi-design-system/.storybook/styles.css
  packages/gmi-design-system/package.json
  packages/gmi-design-system/src/components/index.ts
  packages/gmi-design-system/src/components/readme.md
  packages/gmi-design-system/src/global.css
  packages/gmi-design-system/src/icons/index.ts
  packages/gmi-design-system/src/icons/readme.md
  packages/gmi-design-system/src/index.ts
  packages/gmi-design-system/src/tokens/Color/Color.stories.tsx
  packages/gmi-design-system/src/tokens/Color/Color.tsx
  packages/gmi-design-system/src/tokens/Color/color.css.ts
  packages/gmi-design-system/src/tokens/index.ts
  packages/gmi-design-system/src/tokens/readme.md
  packages/gmi-design-system/tsconfig.build.json
  packages/gmi-design-system/tsconfig.json
  packages/gmi-design-system/tsconfig.node.json
  packages/gmi-design-system/vite.config.ts
Labels: chore

#15 [#11] chore: svgr and headless ui setting with auto gen icon
  .gitignore
  package-lock.json
  packages/client/package.json
  packages/gmi-design-system/package.json
  packages/gmi-design-system/src/component/index.ts
  packages/gmi-design-system/src/component/readme.md
  packages/gmi-design-system/src/icon/asset/icon-bookmark.svg
  packages/gmi-design-system/src/icon/default/IconBookmark.tsx
  packages/gmi-design-system/src/icon/default/index.ts
  packages/gmi-design-system/src/icon/index.ts
  packages/gmi-design-system/src/icon/readme.md
  packages/gmi-design-system/src/icon/shared/props.ts
  packages/gmi-design-system/src/icons/index.ts
  packages/gmi-design-system/src/icons/readme.md
  packages/gmi-design-system/src/index.ts
  packages/gmi-design-system/src/token/Color/Color.stories.tsx
  packages/gmi-design-system/src/token/Color/Color.tsx
  packages/gmi-design-system/src/token/Color/color.css.ts
  packages/gmi-design-system/src/token/index.ts
  packages/gmi-design-system/src/token/readme.md
  packages/gmi-design-system/svgr.config.mjs
  packages/gmi-design-system/tool/svgrIndexTemplate.cjs
Labels: feat, chore

#18 [#17] chore: add workflows
  .github/workflows/web-preview.yml
  package-lock.json
  packages/client/package.json
Labels: chore, operation

#26 [#23] feat: add textarea, textinput, color, button
  package-lock.json
  packages/gmi-design-system/.storybook/main.js
  packages/gmi-design-system/.storybook/preview.js
  packages/gmi-design-system/package.json
  packages/gmi-design-system/src/component/Button/Button.stories.tsx
  packages/gmi-design-system/src/component/Button/Button.tsx
  packages/gmi-design-system/src/component/Button/button.css.ts
  packages/gmi-design-system/src/component/TextArea/TextArea.stories.tsx
  packages/gmi-design-system/src/component/TextArea/TextArea.tsx
  packages/gmi-design-system/src/component/TextArea/textarea.css.ts
  packages/gmi-design-system/src/component/TextInput/TextInput.stories.tsx
  packages/gmi-design-system/src/component/TextInput/TextInput.tsx
  packages/gmi-design-system/src/component/TextInput/textInput.css.ts
  packages/gmi-design-system/src/component/index.ts
  packages/gmi-design-system/src/global.css
  packages/gmi-design-system/src/icon/default/IconBookmark.tsx
  packages/gmi-design-system/src/icon/shared/props.ts
  packages/gmi-design-system/src/token/Color/color.css.ts
  packages/gmi-design-system/src/token/Color/color.ts
  packages/gmi-design-system/tsconfig.node.json
Labels: feat

#27 [NONE] fix: fix capitalized for build err
  packages/client/app/page.tsx
  packages/gmi-design-system/src/token/index.ts
Labels: fix

#29 [#28] feat: add select and icon
  package-lock.json
  packages/gmi-design-system/.storybook/main.js
  packages/gmi-design-system/.storybook/preview.js
  packages/gmi-design-system/package.json
  packages/gmi-design-system/src/component/Select/Select.stories.tsx
  packages/gmi-design-system/src/component/Select/Select.tsx
  packages/gmi-design-system/src/component/Select/select.css.ts
  packages/gmi-design-system/src/component/TextInput/TextInput.stories.tsx
  packages/gmi-design-system/src/component/TextInput/TextInput.tsx
  packages/gmi-design-system/src/component/TextInput/textInput.css.ts
  packages/gmi-design-system/src/icon/asset/icon-arrow-down.svg
  packages/gmi-design-system/src/icon/asset/icon-search.svg
  packages/gmi-design-system/src/icon/default/IconArrowDown.tsx
  packages/gmi-design-system/src/icon/default/IconSearch.tsx
  packages/gmi-design-system/src/icon/default/index.ts
Labels: feat

#30 [#22] feat: add layout with header and bottom
  packages/client/.eslintrc.json
  packages/client/app/(withLayout)/layout.tsx
  packages/client/app/(withLayout)/question/create/page.tsx
  packages/client/app/globals.css
  packages/client/app/layout.tsx
  packages/client/app/readme.md
  packages/client/src/apps/layout/ui/AuthLayout.tsx
  packages/client/src/apps/layout/ui/index.ts
  packages/client/src/pages/home/page.tsx
  packages/client/src/pages/not-found/page.tsx
  packages/client/src/pages/readme.md
  packages/client/src/pages/signin/page.tsx
  packages/client/src/pages/signup/page.tsx
  packages/client/src/shared/model/index.ts
  packages/client/src/shared/model/layout/header.ts
  packages/client/src/shared/model/layout/pageURL.ts
  packages/client/src/shared/ui/Header/Header.tsx
  packages/client/src/shared/ui/Header/header.css.ts
  packages/client/src/shared/ui/NavBar/NavBar.tsx
  packages/client/src/shared/ui/NavBar/navbar.css.ts
  packages/client/src/shared/ui/index.ts
  packages/client/tsconfig.json
  packages/gmi-design-system/src/icon/asset/icon-arrow-left.svg
  packages/gmi-design-system/src/icon/default/IconArrowLeft.tsx
  packages/gmi-design-system/src/icon/default/index.ts
Labels: feat

#21 [#20] style: Pretendard Font setting
  packages/gmi-design-system/src/token/typo/Pretendard.css.ts
  packages/gmi-design-system/src/token/typo/Pretendard.stories.tsx
  packages/gmi-design-system/src/token/typo/PretendardVariable.woff2
  packages/gmi-design-system/src/token/typo/typography.css.ts
Labels: style

#36 [#31] feat: /home 화면 구현
  package-lock.json
  package.json
  packages/client/app/(withLayout)/home/index.css.ts
  packages/client/app/(withLayout)/home/page.tsx
  packages/client/app/(withLayout)/home/slider.css
  packages/client/app/(withLayout)/home/useClientSideRender.ts
  packages/client/app/layout.tsx
  packages/client/package.json
  packages/client/src/features/useScrollHandler.ts
  packages/client/src/shared/data/job.ts
  packages/client/src/shared/ui/QuestionList/Question.css.ts
  packages/client/src/shared/ui/QuestionList/Question.tsx
  packages/client/src/widgets/HomeHeader/HomeHeader.css.ts
  packages/client/src/widgets/HomeHeader/HomeHeader.tsx
  packages/gmi-design-system/src/component/Button/button.css.ts
  packages/gmi-design-system/src/component/Recommend/home/Blue.svg
  packages/gmi-design-system/src/component/Recommend/home/Green.svg
  packages/gmi-design-system/src/component/Recommend/home/HomeRecommend.tsx
  packages/gmi-design-system/src/component/Recommend/home/Orange.svg
  packages/gmi-design-system/src/component/Recommend/home/index.css.ts
  packages/gmi-design-system/src/component/index.ts
  packages/gmi-design-system/src/icon/asset/icon-alarm.svg
  packages/gmi-design-system/src/icon/asset/icon-arrow-right.svg
  packages/gmi-design-system/src/icon/asset/icon-arrow-up.svg
  packages/gmi-design-system/src/icon/asset/icon-likes-default.svg
  packages/gmi-design-system/src/icon/asset/icon-logo.svg
  packages/gmi-design-system/src/icon/asset/readme.md
  packages/gmi-design-system/src/icon/default/IconAlarm.tsx
  packages/gmi-design-system/src/icon/default/IconArrowRight.tsx
  packages/gmi-design-system/src/icon/default/IconArrowUp.tsx
  packages/gmi-design-system/src/icon/default/IconLikesDefault.tsx
  packages/gmi-design-system/src/icon/default/IconLogo.tsx
  packages/gmi-design-system/src/icon/default/index.ts
Labels: feat

#41 [#37] feat: /signup 화면 구현
  packages/client/app/(withLayout)/signup/index.css.ts
  packages/client/app/(withLayout)/signup/page.tsx
  packages/client/app/signup/page.tsx
  packages/client/src/entities/@types/signup.ts
Labels: feat

#46 [#45] fix: localFont 적용
  packages/client/app/layout.tsx
  packages/client/public/font/PretendardVariable.woff2
Labels: fix

#65 [NONE] fix: fix build err
  packages/client/app/(withLayout)/signup/page.tsx
  packages/client/next.config.mjs
  packages/client/tsconfig.json
Labels: fix

#70 [#69] chore: add open api generator
  .gitignore
  package-lock.json
  packages/client/.gitignore
  packages/client/api/.npmignore
  packages/client/api/.openapi-generator-ignore
  packages/client/api/.openapi-generator/FILES
  packages/client/api/.openapi-generator/VERSION
  packages/client/api/api.ts
  packages/client/api/base.ts
  packages/client/api/common.ts
  packages/client/api/configuration.ts
  packages/client/api/git_push.sh
  packages/client/api/index.ts
  packages/client/openapitools.json
  packages/client/package.json
Labels: chore

#42 [#40] feat: 로그인 화면 제작
  packages/client/app/page.tsx
  packages/client/public/asset/Background.svg
  packages/client/src/clientPages/signin/ui/ClientSigninPage.tsx
  packages/client/src/clientPages/signin/ui/index.ts
  packages/client/src/clientPages/signin/ui/signin.css.ts
  packages/client/src/design-system/component/SNSButton/SNSButton.css.ts
  packages/client/src/design-system/component/SNSButton/SNSButton.stories.tsx
  packages/client/src/design-system/component/SNSButton/SNSButton.tsx
  packages/client/src/design-system/component/index.ts
  packages/client/src/design-system/icon/asset/icon-kakao.svg
  packages/client/src/design-system/icon/asset/icon-naver.svg
  packages/client/src/design-system/icon/default/IconKakao.tsx
  packages/client/src/design-system/icon/default/IconNaver.tsx
  packages/client/src/design-system/icon/default/index.ts
  packages/gmi-design-system/src/component/SNSButton/SNSButton.css.ts
  packages/gmi-design-system/src/component/SNSButton/SNSButton.stories.tsx
  packages/gmi-design-system/src/component/SNSButton/SNSButton.tsx
  packages/gmi-design-system/src/component/index.ts
  packages/gmi-design-system/src/icon/asset/icon-kakao.svg
  packages/gmi-design-system/src/icon/asset/icon-naver.svg
  packages/gmi-design-system/src/icon/default/IconKakao.tsx
  packages/gmi-design-system/src/icon/default/IconNaver.tsx
  packages/gmi-design-system/src/icon/default/index.ts
Labels: feat

#50 [#49] feat: 회원가입 api 연결
  .gitignore
  package-lock.json
  packages/client/app/(withLayout)/signup/index.css.ts
  packages/client/app/(withLayout)/signup/page.tsx
  packages/client/package.json
  packages/client/src/design-system/icon/asset/icon-check.svg
  packages/client/src/design-system/icon/asset/icon-error.svg
  packages/client/src/design-system/icon/default/IconCheck.tsx
  packages/client/src/design-system/icon/default/IconError.tsx
  packages/client/src/design-system/icon/default/index.ts
  packages/client/src/features/signup/CheckMail.ts
  packages/client/src/features/signup/Member.ts
  packages/client/src/shared/api/axiosInstance.ts
  packages/client/src/shared/model/signup/handleOnClick.ts
  packages/client/src/shared/utils/LocalStorage.ts
  packages/client/src/shared/utils/tokenHandler.ts
  packages/gmi-design-system/src/icon/asset/icon-check.svg
  packages/gmi-design-system/src/icon/asset/icon-error.svg
  packages/gmi-design-system/src/icon/default/IconCheck.tsx
  packages/gmi-design-system/src/icon/default/IconError.tsx
  packages/gmi-design-system/src/icon/default/index.ts
  packages/gmi-design-system/src/icon/prepare/readme.md
Labels: feat

#82 [#81] feat: navbar style 적용
  packages/client/src/design-system/icon/asset/icon-home.svg
  packages/client/src/design-system/icon/asset/icon-navbar-chat.svg
  packages/client/src/design-system/icon/default/IconHome.tsx
  packages/client/src/design-system/icon/default/IconNavbarChat.tsx
  packages/client/src/design-system/icon/default/index.ts
  packages/client/src/shared/ui/NavBar/NavBar.tsx
  packages/client/src/shared/ui/NavBar/navbar.css.ts
Labels: feat, style

#74 [#58] feat: /chat ui 구현
  packages/client/app/(withLayout)/chat/page.tsx
  packages/client/src/apps/layout/ui/AuthLayout.tsx
  packages/client/src/widgets/chatList/index.ts
  packages/client/src/widgets/chatList/ui/ChatInformation.tsx
  packages/client/src/widgets/chatList/ui/ChatListContainer.tsx
  packages/client/src/widgets/chatList/ui/ChatListHeader.tsx
  packages/client/src/widgets/chatList/ui/style.css.ts
Labels: feat

#86 [#84] feat: 직렬추가 및 백엔드 테스트
  packages/client/api/common.ts
  packages/client/src/clientPages/signup/ui/ClientSignupPage.tsx
  packages/client/src/shared/model/job.ts
  packages/client/src/widgets/SignupInputs/ui/SignupInputSection.tsx
Labels: feat

#87 [#84] remove: 기존 코드로 수정
  packages/client/api/common.ts
Labels: remove

#93 [#54] feat: connect create question api
  packages/client/src/clientPages/questionCreate/ui/ClientQuestionCreatePage.tsx
  packages/client/src/design-system/component/MultiSelect/index.tsx
  packages/client/src/design-system/component/NumberInput/NumberInput.stories.tsx
  packages/client/src/design-system/component/NumberInput/NumberInput.tsx
  packages/client/src/design-system/component/Select/Select.tsx
  packages/client/src/design-system/component/TextArea/TextArea.stories.tsx
  packages/client/src/design-system/component/TextArea/TextArea.tsx
  packages/client/src/design-system/component/TextInput/TextInput.stories.tsx
  packages/client/src/design-system/component/TextInput/TextInput.tsx
  packages/client/src/entities/question/lib/hook/useQuestionCreateForm.ts
  packages/client/src/entities/question/lib/hook/useValidateQuestion.ts
  packages/client/src/entities/question/model/questionFormDefaultValue.ts
  packages/client/src/widgets/QuestionCreateInputs/ui/QuestionCreateInputs.tsx
  packages/client/src/widgets/QuestionUpdateInputs/ui/QuestionUpdateInputs.tsx
  packages/client/src/widgets/SignupInputs/ui/SignupInputSection.tsx
  packages/gmi-design-system/src/component/MultiSelect/index.tsx
  packages/gmi-design-system/src/component/NumberInput/NumberInput.stories.tsx
  packages/gmi-design-system/src/component/NumberInput/NumberInput.tsx
  packages/gmi-design-system/src/component/Select/Select.tsx
  packages/gmi-design-system/src/component/TextArea/TextArea.stories.tsx
  packages/gmi-design-system/src/component/TextArea/TextArea.tsx
  packages/gmi-design-system/src/component/TextInput/TextInput.stories.tsx
  packages/gmi-design-system/src/component/TextInput/TextInput.tsx
Labels: feat

#76 [#75] feat: /account/credit ui 구현
  packages/client/app/(withLayout)/account/credit/page.tsx
  packages/client/public/asset/creditBackground.svg
  packages/client/src/design-system/component/Select/Select.tsx
  packages/client/src/shared/utils/formatNumberWithCommas.ts
  packages/client/src/widgets/AccountCredit/index.ts
  packages/client/src/widgets/AccountCredit/ui/CreditAmount.tsx
  packages/client/src/widgets/AccountCredit/ui/CreditCategoryFilter.tsx
  packages/client/src/widgets/AccountCredit/ui/CreditHistoryContainer.tsx
  packages/client/src/widgets/AccountCredit/ui/CreditList.tsx
  packages/client/src/widgets/AccountCredit/ui/CreditListsContainer.tsx
  packages/client/src/widgets/AccountCredit/ui/style.css.ts
Labels: feat

#99 [#98] fix: 버튼 크기 사이즈 오류 해결
  packages/client/src/design-system/component/NumberInput/NumberInput.tsx
  packages/client/src/design-system/component/NumberInput/numberInput.css.ts
  packages/client/src/design-system/icon/asset/icon-arrow-down.svg
  packages/client/src/design-system/icon/asset/icon-arrow-up.svg
  packages/client/src/design-system/icon/default/IconArrowDown.tsx
Labels: fix, style

#97 [#83] feat: 질문 추천 api 연결
  packages/client/src/clientPages/home/api/getRecommend.ts
  packages/client/src/clientPages/home/ui/ClientHomePage.tsx
  packages/client/src/widgets/Home/ui/Carousel/index.tsx
  packages/client/src/widgets/Home/ui/Recommend/index.css.ts
  packages/client/src/widgets/Home/ui/Recommend/index.tsx
Labels: feat

#96 [#95] feat: connect question list api in Home page
  packages/client/app/(withLayout)/account/question/page.tsx
  packages/client/src/clientPages/home/api/question.ts
  packages/client/src/clientPages/home/ui/ClientHomePage.tsx
  packages/client/src/design-system/icon/asset/icon-likes-default.svg
  packages/client/src/design-system/icon/default/IconLikesDefault.tsx
  packages/client/src/design-system/icon/default/index.ts
  packages/client/src/shared/model/job.ts
  packages/client/src/shared/ui/QuestionList/Question.css.ts
  packages/client/src/shared/ui/QuestionList/Question.tsx
  packages/client/src/widgets/Home/ui/QuestionList/index.tsx
  packages/client/src/widgets/accountBookmark/ui/index.tsx
Labels: feat

#101 [#100] fix: /signup select 디자인 버그 수정 및 직군/직렬 데이터 추가
  packages/client/src/design-system/component/Select/Select.tsx
  packages/client/src/shared/model/job.ts
Labels: feat, fix, style

#102 [none] feat: connect api for question detail
  packages/client/api/api.ts
  packages/client/app/(withLayout)/layout.tsx
  packages/client/app/(withLayout)/question/[id]/page.tsx
  packages/client/src/clientPages/home/ui/ClientHomePage.tsx
  packages/client/src/clientPages/questionCreate/ui/ClientQuestionCreatePage.tsx
  packages/client/src/clientPages/questionDetail/api/answer.ts
  packages/client/src/clientPages/questionDetail/api/question.ts
  packages/client/src/clientPages/questionDetail/index.ts
  packages/client/src/clientPages/questionDetail/ui/ClientQuestionDetailPage.tsx
  packages/client/src/clientPages/questionDetail/ui/style.css.ts
  packages/client/src/clientPages/questionUpdate/api/answer.ts
  packages/client/src/clientPages/questionUpdate/api/question.ts
  packages/client/src/design-system/component/NumberInput/numberInput.css.ts
  packages/client/src/design-system/icon/default/PrimarySmile.tsx
  packages/client/src/entities/question/model/questionFormDefaultValue.ts
  packages/client/src/shared/api/index.ts
  packages/client/src/shared/api/member.ts
  packages/client/src/shared/model/index.ts
  packages/client/src/shared/model/question.ts
  packages/client/src/shared/ui/QuestionList/Question.css.ts
  packages/client/src/shared/util/test.ts
  packages/client/src/widgets/Home/ui/Recommend/index.css.ts
  packages/client/src/widgets/QuestionCreateInputs/ui/QuestionCreateInputs.tsx
  packages/client/src/widgets/QuestionDetail/index.ts
  packages/client/src/widgets/QuestionDetail/ui/AnswerCard.tsx
  packages/client/src/widgets/QuestionDetail/ui/AnswerContainer.tsx
  packages/client/src/widgets/QuestionDetail/ui/QuestionDetailHeader.tsx
  packages/client/src/widgets/QuestionDetail/ui/QuestionInformationBottom.tsx
  packages/client/src/widgets/QuestionDetail/ui/QuestionInformationContainer.tsx
  packages/client/src/widgets/QuestionDetail/ui/style.css.ts
  packages/client/src/widgets/QuestionUpdateInputs/ui/QuestionUpdateInputs.tsx
Labels: feat

#105 [#103] feat: add and refactor icon and fix MultiSelect style
  package.json
  packages/client/app/globals.css
  packages/client/src/clientPages/home/ui/ClientHomePage.tsx
  packages/client/src/design-system/component/MultiSelect/index.tsx
  packages/client/src/design-system/component/SNSButton/SNSButton.tsx
  packages/client/src/design-system/icon/default/IconCharacter.tsx
  packages/client/src/design-system/icon/default/IconChat.tsx
  packages/client/src/design-system/icon/default/IconCheckCircleFilled.tsx
  packages/client/src/design-system/icon/default/IconCheckFilled.tsx
  packages/client/src/design-system/icon/default/IconLikesDefault.tsx
  packages/client/src/design-system/icon/default/IconNaver.tsx
  packages/client/src/design-system/icon/default/IconPlus.tsx
  packages/client/src/design-system/icon/default/IconThumbUp.tsx
  packages/client/src/design-system/icon/default/PrimarySmile.tsx
  packages/client/src/design-system/icon/default/index.ts
  packages/client/src/entities/@types/question.ts
  packages/client/src/entities/@types/signup.ts
  packages/client/src/shared/ui/QuestionList/Question.tsx
  packages/client/src/widgets/Home/ui/Recommend/index.tsx
  packages/client/src/widgets/QuestionDetail/ui/AnswerCard.tsx
  packages/client/src/widgets/QuestionDetail/ui/AnswerContainer.tsx
  packages/gmi-design-system/src/component/MultiSelect/index.tsx
  packages/gmi-design-system/src/component/NumberInput/NumberInput.tsx
  packages/gmi-design-system/src/component/NumberInput/numberInput.css.ts
  packages/gmi-design-system/src/component/Recommend/home/HomeRecommend.tsx
  packages/gmi-design-system/src/component/SNSButton/SNSButton.tsx
  packages/gmi-design-system/src/component/Select/Select.tsx
  packages/gmi-design-system/src/global.css
  packages/gmi-design-system/src/icon/asset/icon-arrow-down.svg
  packages/gmi-design-system/src/icon/asset/icon-arrow-up.svg
  packages/gmi-design-system/src/icon/asset/icon-credit-fill.svg
  packages/gmi-design-system/src/icon/default/IconArrowDown.tsx
  packages/gmi-design-system/src/icon/default/IconCharacter.tsx
  packages/gmi-design-system/src/icon/default/IconChat.tsx
  packages/gmi-design-system/src/icon/default/IconCheckCircle.tsx
  packages/gmi-design-system/src/icon/default/IconCheckFilled.tsx
  packages/gmi-design-system/src/icon/default/IconCreditFill.tsx
  packages/gmi-design-system/src/icon/default/IconLikesDefault.tsx
  packages/gmi-design-system/src/icon/default/IconNaver.tsx
  packages/gmi-design-system/src/icon/default/IconPlus.tsx
  packages/gmi-design-system/src/icon/default/IconThumbUp.tsx
  packages/gmi-design-system/src/icon/default/IconWhiteBookmark.tsx
  packages/gmi-design-system/src/icon/default/PrimarySmile.tsx
  packages/gmi-design-system/src/icon/default/index.ts
  packages/gmi-design-system/tsconfig.json
Labels: refactor
